Vd photogram pundit
viviancreates/industrial-auth-1 pull request #3
Opened 2024-11-04 00:35 UTC by viviancreates

2024-11-05 16:26 UTC, armstrca requested changes
Ideally, users who don't follow a private user should be able to see the private user's profile information without seeing their photos. The assignment gets this wrong despite matchthetarget showing a correct example. I won't grade on that, but it would be good exercise to figure the solution out for yourself.

2024-11-05 16:26 UTC, armstrca commented on app/policies/comment_policy.rb
Edit/delete icons are still showing up for comments that current_user does not own. Clicking on edit prompts a flash error that the user isn't authorized, which is correct, but the icon shouldn't be visible anyway. 

Clicking on delete does not work, which is correct, but causes this error:
![Screenshot 2024-11-05 100224](https://github.com/user-attachments/assets/c9ef6b73-a1c9-49f7-aa6d-ed04d4a3e916)

2024-11-05 16:26 UTC, armstrca commented on app/policies/user_policy.rb
Receive this error when trying to go to `root/:user/discover`
![Screenshot 2024-11-05 101955](https://github.com/user-attachments/assets/add8fa01-9d9b-40cf-93b4-455129a18ff3)

2024-11-05 16:26 UTC, armstrca commented on app/policies/photo_policy.rb
Receive this error when going to `root/:user/liked`

![Screenshot 2024-11-05 102203](https://github.com/user-attachments/assets/1e599b2c-8f35-4eaf-8f5b-1a81e78a2f8e)

2024-11-08 21:26 UTC, AnnaVi11arrea1 requested changes
Need to just define some methods in your users controller. :)

2024-11-08 21:26 UTC, AnnaVi11arrea1 commented on app/controllers/users_controller.rb
![Screenshot 2024-11-08 152222](https://github.com/user-attachments/assets/7b7269f2-5e78-405d-9078-40094a4a4e98)
You need to define a liked method in your users controller. :)

2024-11-08 21:26 UTC, AnnaVi11arrea1 commented on app/controllers/users_controller.rb
![Screenshot 2024-11-08 152502](https://github.com/user-attachments/assets/3daf2156-ef16-40d0-a425-c9183337b215)
Also need to define a discover method in users controller.

2024-11-11 19:14 UTC, armstrca requested changes
The `delete` button doesn't seem to work for comments, but otherwise this looks good.

2024-11-14 18:27 UTC, merged